### ISSUE TITLE
How add controlnet and lora to colab ?

### ISSUE THREAD

**Issue by Kingal20000** [MikeEmmett/InvokeAI#2]

**Comment by ImMikeEmmett** [comment]
Hello!
I will add this functionality soon.
First I am going to remove support for V2.3.5.post2 (and move it to a different Branch)
As since a recent update V3 is stable and backwards compatibility is no longer really needed.
This will also allow for changes to be made faster as It does not need to be added to both versions.

**Comment by ImMikeEmmett** [comment]
This has been implemented, it has not been thoroughly tested, as I have never used them myself. 
It has successfully imported the models for use from both HuggingFace and a direct URL to a .safetensors file.
